[package]
name = "runtrue-gha-import"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true

[dependencies]
runtrue-compiler.workspace = true
runtrue-lock.workspace = true
runtrue-workflow-ast.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
