[package]
name = "runtrue-secrets"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true

[dependencies]
runtrue-model.workspace = true
base64ct.workspace = true
chacha20poly1305.workspace = true
hex.workspace = true
rand_core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
ureq.workspace = true
x509-parser.workspace = true
zeroize.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[dev-dependencies]
rcgen.workspace = true
tempfile.workspace = true

[lints]
workspace = true
