# syntax=docker/dockerfile:1.10@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5
ARG RUST_IMAGE=docker.io/library/rust:1.94.0-bookworm@sha256:365468470075493dc4583f47387001854321c5a8583ea9604b297e67f01c5a4f
ARG RUNTIME_IMAGE=docker.io/library/debian:bookworm-20250630-slim@sha256:6ac2c08566499cc2415926653cf2ed7c3aedac445675a013cc09469c9e118fdd

FROM ${RUST_IMAGE} AS build
ENV RUSTUP_TOOLCHAIN=1.94.0
WORKDIR /src
COPY . .
RUN --mount=type=cache,id=runtrue-cargo-registry-v1,target=/usr/local/cargo/registry,sharing=locked \
    --mount=type=cache,id=runtrue-cargo-git-v1,target=/usr/local/cargo/git,sharing=locked \
    --mount=type=cache,id=runtrue-rust-1.94-release-target-v1,target=/src/target,sharing=locked \
    cargo build --locked --release -p runtrue-autoscaler-bin --bin runtrue-autoscaler && \
    install -D -m 0555 target/release/runtrue-autoscaler /out/runtrue-autoscaler

FROM ${RUNTIME_IMAGE}
ARG RUNTRUE_VERSION=0.1.0
ARG RUNTRUE_REVISION=unknown
LABEL org.opencontainers.image.title="Runtrue autoscaler" \
      org.opencontainers.image.version="${RUNTRUE_VERSION}" \
      org.opencontainers.image.revision="${RUNTRUE_REVISION}" \
      org.opencontainers.image.licenses="Apache-2.0"
COPY --from=build --chown=0:0 /out/runtrue-autoscaler /usr/local/bin/runtrue-autoscaler
RUN chmod 0555 /usr/local/bin/runtrue-autoscaler
USER 65532:65532
STOPSIGNAL SIGTERM
ENTRYPOINT ["/usr/local/bin/runtrue-autoscaler"]
