[package]
name = "runtrue-update-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true

[[bin]]
name = "runtrue-update"
path = "src/main.rs"

[[bin]]
name = "runtrue-updater"
path = "src/updater_main.rs"

[dependencies]
runtrue-model.workspace = true
runtrue-update.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true
nix = { workspace = true, features = ["user"] }
ed25519-dalek.workspace = true
rand_core.workspace = true
zeroize.workspace = true
hex.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
