[package]
name = "runtrue-artifacts"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true

[dependencies]
runtrue-attest.workspace = true
runtrue-model.workspace = true
runtrue-storage.workspace = true
nix.workspace = true
rand_core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
runtrue-workflow-ir.workspace = true
tempfile.workspace = true

[lints]
workspace = true
